### ISSUE TITLE
Add Tangram enum

### ISSUE THREAD

**Issue by jespirit** [PopeSpaceous/Solitary#137]
There should be a tangram `enum` for the types of tangrams. It makes the code easier to follow.

I believe the `type` of a tangram is explicitly set in Unity. For example, the `PuzzleTangram` game object contains 7 tangrams and is created on startup and then populated with a random set of coordinates. So the order in which the enums are declared is important.

```cs
public enum TangramType
{
    Square = 1,
    Parallelogram,
    SmallTriangle,
    MediumTriangle,
    LargeTriangle
}
```

**Comment by PopeSpaceous** [comment]
Agreed. It would be a lot easier to follow (square rather than 1)

**Comment by PopeSpaceous** [comment]
Enums are made, Closing this issue.
